#!/bin/bash

# To clear containers:
docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)

# To clear volumes:
docker volume rm $(docker volume ls -q)

# To clear networks:
docker network rm $(docker network ls | tail -n+2 | awk '{if($2 !~ /bridge|none|host/){ print $1 }}')

# If something is still missing
docker system prune -a
